2024-10-08 22:04:59,388 | ERROR : Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\weq\PycharmProjects\module_11_3\test_12_1.py\test_12_4.py", line 51, in test_run
    run1 = Runner(56)
           ^^^^^^^^^^
  File "C:\Users\weq\PycharmProjects\module_11_3\test_12_1.py\test_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-08 22:04:59,391 | ERROR : Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\weq\PycharmProjects\module_11_3\test_12_1.py\test_12_4.py", line 39, in test_walk
    walk1 = Runner('First', -5)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\weq\PycharmProjects\module_11_3\test_12_1.py\test_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
